//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeetingMinutesGP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meeting
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Meeting()
        {
            this.Agenda = new HashSet<Agendum>();
            this.UserMeetings = new HashSet<UserMeeting>();
        }
    
        public int MeetingID { get; set; }
        public Nullable<double> MeetingDuration { get; set; }
        public System.DateTime MeetingDate { get; set; }
        public string Status { get; set; }
        public Nullable<int> locationID { get; set; }
        public string ReferenceLinkName { get; set; }
        public string ReferenceLink { get; set; }
        public string ImageLocation { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Agendum> Agenda { get; set; }
        public virtual Location Location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserMeeting> UserMeetings { get; set; }
    }
}
