//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeetingMinutesGP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int NotificaionId { get; set; }
        public bool IsRead { get; set; }
        public string Message { get; set; }
        public string DetailsURL { get; set; }
        public System.DateTime Date { get; set; }
        public int UserId { get; set; }
        public int MeetingId { get; set; }
        public Nullable<int> VoteID { get; set; }
    
        public virtual UserMeeting UserMeeting { get; set; }
        public virtual Vote Vote { get; set; }
    }
}
