//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeetingMinutesGP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Option
    {
        public int OptionID { get; set; }
        public string OptionDescription { get; set; }
        public int voteID { get; set; }
        public int OptionCount { get; set; }
    
        public virtual Vote Vote { get; set; }
    }
}
