//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeetingMinutesGP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMeeting
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserMeeting()
        {
            this.Notifications = new HashSet<Notification>();
        }
    
        public int userID { get; set; }
        public int meetingID { get; set; }
        public bool Attended { get; set; }
        public string AssignedTask { get; set; }
        public Nullable<System.DateTime> TaskStartDate { get; set; }
        public Nullable<System.DateTime> TaskEndDate { get; set; }
        public Nullable<bool> Coordinator { get; set; }
        public string TaskDescription { get; set; }
        public string TaskStatus { get; set; }
        public int CalendarTaskID { get; set; }
        public string TaskIntiatorEmail { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notification> Notifications { get; set; }
        public virtual Meeting Meeting { get; set; }
    }
}
